echo Downloading data...
scp mnas@v.vectorinstitute.ai:/checkpoint/gshensvm/BAISO_checkpoints/data/train-balanced-sarcasm-processed.csv civility/recommender/

echo Downloading civility filter checkpoint...
mkdir civility/classifier/results/
scp -r mnas@v.vectorinstitute.ai:/checkpoint/gshensvm/BAISO_checkpoints/model_checkpoints/civility_model civility/classifier/results/final_model

echo Downloading diversity embeddings...
scp -r mnas@v.vectorinstitute.ai:/checkpoint/gshensvm/BAISO_checkpoints/embeddings diversity/datasets/

echo Downloading recommender engine checkpoint...
mkdir demo/data
scp -r mnas@v.vectorinstitute.ai:/checkpoint/gshensvm/BAISO_checkpoints/model_checkpoints/recommender_model civility/recommender/final_model
